version: "3.8"

# Can't use DOCKER_HOST:
# https://stackoverflow.com/questions/35072611/unable-to-use-variable-substitution-in-docker-compose

# Need to make a ./secrets folder with two files:
# NORDVPN_USER
# NORDVPN_PASSWORD
services:
  nordvpn:
    image: nordvpn:latest
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 1500M
      restart_policy:
        condition: on-failure
    environment:
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    volumes:
      - ./secrets:/run/secrets

  nordvpn-privoxy:
    image: nordvpn-privoxy:latest
    ports:
      - 8118:8118
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
