version: "3.8"

# Can't use DOCKER_HOST:
# https://stackoverflow.com/questions/35072611/unable-to-use-variable-substitution-in-docker-compose

services:
  nordvpn:
    image: nordvpn:latest
    user: root
    deploy:
      resources:
        limits:
          memory: 1500M
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    secrets:
      - NORDVPN_USER
      - NORDVPN_PASSWORD
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required

secrets:
  NORDVPN_USER:
    external: true
  NORDVPN_PASSWORD:
    external: true