version: "3.8"

# Can't use DOCKER_HOST:
# https://stackoverflow.com/questions/35072611/unable-to-use-variable-substitution-in-docker-compose

# Need to make a ./secrets folder with two files:
# NORDVPN_USER
# NORDVPN_PASSWORD

#@ https://jordanelver.co.uk/blog/2019/06/03/routing-docker-traffic-through-a-vpn-connection/
services:
  nordvpn:
    image: nordvpn:latest
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 1500M
      restart_policy:
        condition: any
    command: "/usr/bin/start_vpn.sh ; /usr/local/bin/privoxy-start.sh"
    environment:
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun            # Required
    volumes:
      - ./secrets:/run/secrets
    # A bit strange, but we need to expose the ports of the privoxy container here.
    ports:
      - 8118:8118
